# -*- coding: utf-8 -*-


[ID_MNUUNDO, ID_MNUREDO, ID_MNUFILEOPEN, ID_MNUFILESAVE, ID_MNUFILESAVEAS, 
 ID_MNUFILEPRINT, ID_MAIN_TOOLBAR, ADD_User, DEL_User, EDIT_User,
 ADD_Event, DEL_Event] = range(12)